### ISSUE TITLE
Can't Deploy on container running on Centos 7

### ISSUE THREAD

**Issue by andyg5000** [mingfang/docker-predictionio#10]
I'm getting the following error after attempting the quick start run.sh script in a docker container. I'm not expert in parsing java barf, but I'm not sure why there would be an RDNS issue 

Exception in thread "main" java.lang.NullPointerException
	at org.apache.hadoop.net.DNS.reverseDns(DNS.java:92)
	at org.apache.hadoop.hbase.mapreduce.TableInputFormatBase.reverseDNS(TableInputFormatBase.java:228)
	at org.apache.hadoop.hbase.mapreduce.TableInputFormatBase.getSplits(TableInputFormatBase.java:191)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:98)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:205)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:203)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:203)
	at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:205)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:203)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:203)
	at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:205)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:203)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:203)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1060)
	at org.template.recommendation.ALSAlgorithm.train(ALSAlgorithm.scala:28)
	at org.template.recommendation.ALSAlgorithm.train(ALSAlgorithm.scala:21)
	at io.prediction.controller.PAlgorithm.trainBase(Algorithm.scala:136)
	at io.prediction.workflow.CoreWorkflow$$anonfun$24$$anonfun$25.apply(Workflow.scala:603)
	at io.prediction.workflow.CoreWorkflow$$anonfun$24$$anonfun$25.apply(Workflow.scala:602)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at io.prediction.workflow.CoreWorkflow$$anonfun$24.apply(Workflow.scala:602)
	at io.prediction.workflow.CoreWorkflow$$anonfun$24.apply(Workflow.scala:598)
	at scala.collection.parallel.AugmentedIterableIterator$class.map2combiner(RemainsIterator.scala:120)
	at scala.collection.parallel.immutable.ParHashMap$ParHashMapIterator.map2combiner(ParHashMap.scala:79)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1057)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1054)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
	at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:444)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:514)
	at scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Tasks.scala:492)
	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:64)
	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:961)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:956)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
You may now deploy engine by running cd /quickstartapp/MyRecommendation && pio deploy --ip 0.0.0.0
root@c67befe774d2:/quickstartapp# cd /quickstartapp/MyRecommendation && pio deploy --ip 0.0.0.0
2015-03-06 02:46:18,649 ERROR tools.Console$ - No valid engine instance found for engine DECkRLUML0JtjBzIW2YuGlCv5rKIJn4k d226d35564d904d3c6610458191c461c1b2fc9ff.
Try running 'train' before 'deploy'. Aborting.

**Comment by andyg5000** [comment]
This issue happened when building predictionio manually in a docker container as well. I was able to get around the problem by setting up dnsmasq and creating records that map the docker container hostname to 127.0.0.1. I'm not sure why this doesn't work with plain ol /etc/hosts

**Comment by andyg5000** [comment]
Somehow I never landed on the http://docs.prediction.io/resources/faq/. Since I don't have a local DNS server returning reverse dns for my containers this would fail. Adding --dns=8.8.8.8 in my docker run command resolved the issue for testing

docker run -it --dns=8.8.8.8.....

**Comment by vallettea** [comment]
:+1: thx
